spring:
  datasource:
    url: jdbc:h2:mem:shareit;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: never    # не пытаться запускать schema.sql/data.sql в тестах
  flyway:
    enabled: false   # на всякий случай
  liquibase:
    enabled: false
