spring:
  datasource:
    url: jdbc:h2:mem:shareit;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.test.context: INFO
    org.hibernate.SQL: WARN
